### ISSUE TITLE
EPIC: Setup repositories and build/release automation for community repositories

### ISSUE THREAD

**Issue by olljanat** [rancher-os-community/os#4]
As I'm currently working alone with this repository I will use this issue to keep track about progress.

TODO:
* Setup build/release automation for all needed repositories
  * [ ] os
  * [ ] os-kernel
  * [x] os-services
* [ ] Get at least 5 maintainers to project: #2
* [x] Remove old branches from forked repositories
* [x] Remove old releases from forked repositories
* [ ] Get new name for project #3 
* [ ] Update readme to all the repositories
* [ ] Update license file to all the repositories
* [ ] Split OS documentation from Rancher other documentations
* [ ] Replace Rancher trademark references from all the code and documentation files (except from those where we need keep mention based on Apache 2 license requirements.

**Comment by olljanat** [comment]
Sort status info.

For me v1.9.0-beta2 looks very good. Just some minor bugs need to be fixed and then IMO we are ready to move release candidate phase. For me v1.9.0 version release is on highest priority.

Other quite important thing would be to get side navigation to documentation #11 so we can start instruct users to move from RancherOS to BurmillaOS.

v2.0.0 will need more work before it will works correctly so I have no actually idea yet how long it will take.

Anyway, I created now projects to https://github.com/burmilla/os/projects and I will start connect issues to those and also label them so it will be easier to follow progress.
